INSERT INTO TB_AIRCRAFT(AIRCRAFT_ID, AIRCRAFT_BADGE, AIRCRAFT_MODEL, AIRCRAFT_BRAND) VALUES (1, 'ABC-123' ,'AIR-01', 'Airbus');

INSERT INTO TB_ORIGIN VALUES ('1', 'GRU', 'Guarulhos');
INSERT INTO TB_DESTINATION VALUES ('1', 'GRU', 'Guarulhos');